user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
